### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by khygge** [Bram-G/Board-Game-Party#7]
###User Story
As a developer, I want to see a wireframe with a clear layout, so that it is easy to reference to build.
###Acceptance Criteria
Given a wireframe, we can see clearly labelled sections with elements represented inside of it, so we can build the website.

**Comment by Bram-G** [comment]
![Image](https://user-images.githubusercontent.com/119541508/211895926-2734cb9c-b452-4d6f-87dc-821fbbf2590b.jpg)
